_target_: src.models.plain_ae.AELightningModule
optimizer: 
  _target_: torch.optim.Adam
  lr: 0.0002
  betas: 
  - 0.9 
  - 0.99
decoder:
  _target_: src.models.components.autoencoder_network.Shape_Decoder
  code_dim: 2
  output_channels: 1
  vae: False
encoder: 
  _target_: src.models.components.autoencoder_network.Shape_Encoder
  code_dim: 2
  input_channels: 1  

