_target_: src.models.hae.HAELightingModule

optimizer: 
  _target_: torch.optim.Adam
  _partial_: True
  lr: 0.0002
  betas: 
  - 0.9 
  - 0.99
  
encoder: 
  _target_: src.models.components.autoencoder_network.Shape_Encoder
  code_dim: 2
  input_channels: 1   

decoder:
  _target_: src.models.components.autoencoder_network.Shape_Decoder
  code_dim: 2
  output_channels: 1
  vae: False

hlle: 
  _target_: sklearn.manifold.LocallyLinearEmbedding
  method: hessian
  n_neighbors: 40
  n_components: 2
  eigen_solver: 'dense'

ica:
  _target_: sklearn.decomposition.FastICA
  n_components: 2
  whiten: warn
